// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blhjvrredizujcxvjmzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsaGp2cnJlZGl6dWpjeHZqbXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzUyNjIsImV4cCI6MjA2Mzc1MTI2Mn0.pCmwqh9zUAtueH6HRQCV5EjF_lvvQKcnoY164pHlWV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);